#!/bin/bash

case $# in
0) echo
   echo "Usage: `basename $0` [Command]"
   echo
   echo "Examples:"
   echo "          `basename $0` up -d"
   echo "          `basename $0` down"
   echo
   exit 1
   ;;
*) ;;
esac

docker-compose \
    --project-name erpm \
    -f installation/docker-compose-common.yml \
    -f installation/docker-compose-erpnext.yml \
    -f installation/erpnext-publish.yml \
    "$@"

