#!/bin/bash

read -p 'ERPNext version (e.g. v13.21.0): ' ERPNEXT_VERSION
echo

echo -n "Migrating ..."

docker run --rm \
    -e "MAINTENANCE_MODE=1" \
    -v erpm_sites-vol:/home/frappe/frappe-bench/sites \
    --network erpm_default \
    frappe/erpnext-worker:${ERPNEXT_VERSION} migrate "$@"

echo " DONE"

