#!/bin/bash

read -p 'SITE subdomain (i.e. SITE.titusgt.com): ' SITE
read -p 'Administrator password: ' -s ADMIN_PASSWORD
echo
read -p 'MySQL root password: ' -s MYSQL_ROOT_PASSWORD
echo
read -p 'ERPNext version (e.g. v13.21.0): ' ERPNEXT_VERSION
echo 

echo -n "Creating site ${SITE}.titusgt.com ..."

docker run --rm \
    -e "SITE_NAME=${SITE}.titusgt.com" \
    -e "DB_ROOT_USER=root" \
    -e "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}" \
    -e "ADMIN_PASSWORD=${ADMIN_PASSWORD}" \
    -e "INSTALL_APPS=erpnext" \
    -v erpm_sites-vol:/home/frappe/frappe-bench/sites \
    --network erpm_default \
    frappe/erpnext-worker:${ERPNEXT_VERSION} new

echo " DONE"

